param(
    [string]$ProjectPath = (Get-Location).Path,
    [string]$ProjectName = "Godot Game"
)

$ErrorActionPreference = "Stop"

$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-TextFile {
    param(
        [string]$Path,
        [string]$Value
    )
    [System.IO.File]::WriteAllText($Path, $Value, $script:Utf8NoBom)
}

if (-not (Test-Path -LiteralPath $ProjectPath)) {
    New-Item -ItemType Directory -Path $ProjectPath | Out-Null
}

$resolvedProject = (Resolve-Path -LiteralPath $ProjectPath).ProviderPath
$projectFile = Join-Path $resolvedProject "project.godot"
if (Test-Path -LiteralPath $projectFile) {
    throw "project.godot already exists at $projectFile"
}

$scenesDir = Join-Path $resolvedProject "scenes"
$scriptsDir = Join-Path $resolvedProject "scripts"
$assetsDir = Join-Path $resolvedProject "assets"
$artDir = Join-Path $resolvedProject "art"
$audioDir = Join-Path $resolvedProject "audio"
$uiDir = Join-Path $resolvedProject "ui"
$resourcesDir = Join-Path $resolvedProject "resources"
$docsDir = Join-Path $resolvedProject "docs"
$testsDir = Join-Path $resolvedProject "tests"
$exportsDir = Join-Path $resolvedProject "exports"

foreach ($dir in @($scenesDir, $scriptsDir, $assetsDir, $artDir, $audioDir, $uiDir, $resourcesDir, $docsDir, $testsDir, $exportsDir)) {
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }
}

foreach ($dir in @(
    (Join-Path $assetsDir "sprites"),
    (Join-Path $assetsDir "textures"),
    (Join-Path $assetsDir "ui"),
    (Join-Path $assetsDir "vfx"),
    (Join-Path $artDir "concepts"),
    (Join-Path $artDir "source"),
    (Join-Path $audioDir "sfx"),
    (Join-Path $audioDir "music")
)) {
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }
}

$escapedName = $ProjectName.Replace('"', '\"')

Write-TextFile -Path $projectFile -Value @"
; Engine configuration file.
; This file is generated by godot-game-studio-agent.

config_version=5

[application]

config/name="$escapedName"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.0")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720

[rendering]

renderer/rendering_method="gl_compatibility"
"@

Write-TextFile -Path (Join-Path $scenesDir "main.tscn") -Value @"
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="Label" type="Label" parent="."]
offset_left = 24.0
offset_top = 24.0
offset_right = 520.0
offset_bottom = 72.0
text = "Game Studio Agent Godot project ready."
"@

Write-TextFile -Path (Join-Path $scriptsDir "main.gd") -Value @"
extends Node2D

func _ready() -> void:
    print("Game Studio Agent Godot project ready.")
"@

Write-Host "Created Godot project at $resolvedProject"
